[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc_version = "0.8.26"

optimizer = true
optimizer_runs = 200
# fix forge bug which auto remaps to lib/v4-core/src
remappings = [
    "v4-core/=lib/v4-periphery/lib/v4-core/",
    "aegis-dfm/=lib/AEGIS_DFM/src/",
]

fs_permissions = [
    { access = "read", path = "./script/config" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
sepolia = { key = "" }
